# task setup
task: ner
zero_shot_transfer: False
transfer_source: None
langs: ['hi']
dataset_path: data/ner-mono
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: models/hindi/cpt-full_emb-32k-focus/best-checkpoint
tokenizer_path: tokenizers/hi_spm_32k.model
checkpoint_path: models/hindi/ner/xlmr_cpt-full_emb-32k-focus

# training options
random_seed: 1
epochs: 16
batch_size: 36
gradient_accumulation: 1
max_seq_length: 256
max_train_examples: 32768
# checkpoints every two epochs, so patience epochs is this parameter x2
patience: 2